@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-down-> "1" UniquePersonList
UniquePersonList -down-> Person

Person *-left-> "1" Role
Person *--> "1" Name
Person *--> "1" Phone
Person *--> "0..1" Email
Person *--> "0..1" Address
Person *--> "0..1" Remark

HealthcareStaff -left-|> Person
HealthcareStaff *--> "0..1" ProviderRole
HealthcareStaff *--> "0..1" Department

Patient --|> Person
Patient *--> "0..1" Department
Patient *--> "0..1" NextOfKin
Patient *--> "0..1" DoctorInChrge

HealthcareStaff -[hidden]up--> Patient
@enduml
